#!/usr/bin/env python3
"""Team-history sidecar for the MLB pools: the clubs each player wore, per
career and per decade window, ordered by years played (most first). Names are
the era-correct club names from Teams.csv, so Ruth's last stop is the Boston
Braves, not Atlanta. Kept separate from build-mlb-pools.py on purpose — this
is presentation metadata looked up by player id at render time, so the card
math can regenerate without touching it (and vice versa).

Windows are stored under every real decade AND under the merged pre-1920
window (1910) that the pool build folds early baseball into, so the lookup
works against either generation of mlbPools.js.

Data: Baseball Databank (Chadwick Baseball Bureau / Sean Lahman, CC BY-SA).
Writes mlbTeams.js next to this script; copy it to src/data/.
"""
import csv, json, os, sys
from collections import defaultdict

SP = os.path.dirname(os.path.abspath(__file__))
L = os.path.join(SP, "lahman")

def rows(name):
    # utf-8-sig: some databank releases ship with a BOM, which would otherwise
    # corrupt the first header name (yearID) and zero out every year.
    with open(os.path.join(L, name), newline="", encoding="utf-8-sig", errors="replace") as f:
        yield from csv.DictReader(f)

def num(row, key):
    value = row.get(key, "") or "0"
    try:
        return int(value)
    except ValueError:
        return 0

# Mirrors EARLIEST in build-mlb-pools.py: decades through the 1910s merge
# into one "1910s & earlier" window.
EARLIEST = 1910

team_name = {}
for r in rows("Teams.csv"):
    team_name[(num(r, "yearID"), r["teamID"])] = r["name"]

# pid -> window ("all" or decade string) -> club name -> set of years worn.
seen = defaultdict(lambda: defaultdict(lambda: defaultdict(set)))
# Career volume (PA + IPouts) gates the output: anyone too small to ever earn
# a card in any pool stays out of the file. Kept well under the pool build's
# thresholds (250 PA / 225 IPouts per decade) so threshold tweaks over there
# don't orphan cards here.
volume = defaultdict(int)
for source, vol_keys in (("Batting.csv", ("AB", "BB")), ("Pitching.csv", ("IPouts",))):
    for r in rows(source):
        year = num(r, "yearID")
        pid = r["playerID"]
        name = team_name.get((year, r.get("teamID", "")))
        if not name:
            continue
        decade = (year // 10) * 10
        windows = {"all", str(decade), str(EARLIEST) if decade <= EARLIEST else str(decade)}
        for window in windows:
            seen[pid][window][name].add(year)
        volume[pid] += sum(num(r, k) for k in vol_keys)

TEAM_LIST = []
TEAM_INDEX = {}

def ordered(teams):
    """Club-name indexes, most years worn first; ties break to the earlier
    stop, then alphabetically, so the list reads as a stable career arc."""
    ranked = sorted(teams.items(), key=lambda kv: (-len(kv[1]), min(kv[1]), kv[0]))
    out = []
    for name, _ in ranked:
        if name not in TEAM_INDEX:
            TEAM_INDEX[name] = len(TEAM_LIST)
            TEAM_LIST.append(name)
        out.append(TEAM_INDEX[name])
    return out

players = {}
for pid in sorted(seen):
    if volume[pid] < 150:
        continue
    players[pid] = {window: ordered(teams) for window, teams in sorted(seen[pid].items())}

header = """// Which clubs each MLB-pool player wore, per career ("all") and per decade
// window, as indexes into MLB_TEAM_NAMES ordered by years played (most
// first). Built from the Baseball Databank (Chadwick Baseball Bureau / Sean
// Lahman, CC BY-SA 3.0 — https://github.com/chadwickbureau/baseballdatabank).
// Generated by scripts/build-mlb-teams.py; do not hand-edit.
"""
with open(os.path.join(SP, "mlbTeams.js"), "w") as f:
    f.write(header)
    f.write("export const MLB_TEAM_NAMES = ")
    f.write(json.dumps(TEAM_LIST, separators=(",", ":")))
    f.write(";\n")
    f.write("export const MLB_PLAYER_TEAMS = {\n")
    for pid, windows in players.items():
        f.write(json.dumps(pid) + ":" + json.dumps(windows, separators=(",", ":")) + ",\n")
    f.write("};\n")
print(f"wrote mlbTeams.js: {len(players)} players, {len(TEAM_LIST)} club names", file=sys.stderr)
