#!/usr/bin/env python3
"""Team-history sidecar for the MLB pools: the clubs each player wore, per
career and per decade window, ordered by years played (most first). Clubs are
the era-correct Baseball-Reference codes from Teams.csv (teamIDBR): modern
stops read the familiar STL / NYM / KCR, and Ruth's last stop is BSN (the
Boston Braves), not ATL. A club that merely changed names keeps one code —
Grooms, Superbas, and Robins all fold into BRO — so renames don't pad the
list. Kept separate from build-mlb-pools.py on purpose — this
is presentation metadata looked up by player id at render time, so the card
math can regenerate without touching it (and vice versa).

Windows are stored under every real decade AND under the merged pre-1920
window (1910) that the pool build folds early baseball into, so the lookup
works against either generation of mlbPools.js.

Data: Baseball Databank (Chadwick Baseball Bureau / Sean Lahman, CC BY-SA).
Writes mlbTeams.js next to this script; copy it to src/data/.
"""
import csv, json, os, sys
from collections import defaultdict

SP = os.path.dirname(os.path.abspath(__file__))
L = os.path.join(SP, "lahman")

def rows(name):
    # utf-8-sig: some databank releases ship with a BOM, which would otherwise
    # corrupt the first header name (yearID) and zero out every year.
    with open(os.path.join(L, name), newline="", encoding="utf-8-sig", errors="replace") as f:
        yield from csv.DictReader(f)

def num(row, key):
    value = row.get(key, "") or "0"
    try:
        return int(value)
    except ValueError:
        return 0

# Mirrors EARLIEST in build-mlb-pools.py: decades through the 1910s merge
# into one "1910s & earlier" window.
EARLIEST = 1910

team_code = {}
# code -> the club name from the code's LAST season, for logo lookups and
# alt text: MON reads "Montreal Expos", TBD "Tampa Bay Devil Rays" — the
# era-correct code picks the era-correct club.
club_name = {}
for r in rows("Teams.csv"):
    code = r.get("teamIDBR") or r["teamID"]
    year = num(r, "yearID")
    team_code[(year, r["teamID"])] = code
    if code not in club_name or year > club_name[code][0]:
        club_name[code] = (year, r["name"])

# pid -> window ("all" or decade string) -> club code -> set of years worn.
seen = defaultdict(lambda: defaultdict(lambda: defaultdict(set)))
# Career volume (PA + IPouts) gates the output: anyone too small to ever earn
# a card in any pool stays out of the file. Kept well under the pool build's
# thresholds (250 PA / 225 IPouts per decade) so threshold tweaks over there
# don't orphan cards here.
volume = defaultdict(int)
for source, vol_keys in (("Batting.csv", ("AB", "BB")), ("Pitching.csv", ("IPouts",))):
    for r in rows(source):
        year = num(r, "yearID")
        pid = r["playerID"]
        code = team_code.get((year, r.get("teamID", "")))
        if not code:
            continue
        decade = (year // 10) * 10
        windows = {"all", str(decade), str(EARLIEST) if decade <= EARLIEST else str(decade)}
        for window in windows:
            seen[pid][window][code].add(year)
        volume[pid] += sum(num(r, k) for k in vol_keys)

TEAM_LIST = []
TEAM_INDEX = {}

def ordered(teams):
    """Club-code indexes, most years worn first; ties break to the earlier
    stop, then alphabetically, so the list reads as a stable career arc."""
    ranked = sorted(teams.items(), key=lambda kv: (-len(kv[1]), min(kv[1]), kv[0]))
    out = []
    for code, _ in ranked:
        if code not in TEAM_INDEX:
            TEAM_INDEX[code] = len(TEAM_LIST)
            TEAM_LIST.append(code)
        out.append(TEAM_INDEX[code])
    return out

players = {}
for pid in sorted(seen):
    if volume[pid] < 150:
        continue
    players[pid] = {window: ordered(teams) for window, teams in sorted(seen[pid].items())}

header = """// Which clubs each MLB-pool player wore, per career ("all") and per decade
// window, as indexes into MLB_TEAM_CODES (era-correct Baseball-Reference
// abbreviations) ordered by years played (most first). Built from the
// Baseball Databank (Chadwick Baseball Bureau / Sean Lahman, CC BY-SA 3.0 —
// https://github.com/chadwickbureau/baseballdatabank).
// Generated by scripts/build-mlb-teams.py; do not hand-edit.
"""
with open(os.path.join(SP, "mlbTeams.js"), "w") as f:
    f.write(header)
    f.write("export const MLB_TEAM_CODES = ")
    f.write(json.dumps(TEAM_LIST, separators=(",", ":")))
    f.write(";\n")
    f.write("export const MLB_PLAYER_TEAMS = {\n")
    for pid, windows in players.items():
        f.write(json.dumps(pid) + ":" + json.dumps(windows, separators=(",", ":")) + ",\n")
    f.write("};\n")
    f.write("// Each code's club name from its final season, for logo lookups.\n")
    f.write("export const MLB_TEAM_CLUB_NAMES = ")
    f.write(json.dumps({code: name for code, (year, name) in sorted(club_name.items())}, separators=(",", ":")))
    f.write(";\n")
print(f"wrote mlbTeams.js: {len(players)} players, {len(TEAM_LIST)} club codes", file=sys.stderr)
