#!/usr/bin/env python3
"""Emit src/data/classicCards.js from the parsed scouting-report facts."""
import json, os, re, sys

SP = os.path.dirname(os.path.abspath(__file__))
cards = json.load(open(os.path.join(SP, "classic-raw.json")))

# Unique-name -> MLBAM id, for official headshots on the real cards.
import csv as _csv
try:
    _mlbam = json.load(open(os.path.join(SP, "mlbam-map.json")))
    _names = {}
    for _r in _csv.DictReader(open(os.path.join(SP, "lahman", "People.csv"), encoding="utf-8-sig")):
        _n = f"{_r.get('nameFirst') or ''} {_r.get('nameLast') or ''}".strip()
        if _n in _names:
            _names[_n] = None  # ambiguous name: skip
        else:
            _names[_n] = _mlbam.get(_r["playerID"])
    NAME_MLBAM = {k: v for k, v in _names.items() if v}
except FileNotFoundError:
    NAME_MLBAM = {}

RESULT_CODE = {"PU": "P", "SO": "K", "GB": "G", "FB": "F", "W": "W", "S": "S", "S+": "+", "DB": "D", "TR": "T", "HR": "H"}
SPEED_LETTERS = {"A": 20, "B": 15, "C": 10}
POS_MAP = {"LF-RF": "LF/RF", "OF": "CF", "IF": "SS", "---": "DH"}

def primary_position(positions):
    first = positions.split("|")[0].strip()
    m = re.match(r"^([A-Za-z0-9\-]+?)\s*([+-]\d+)?$", first.replace(" ", ""))
    pos = (m.group(1) if m else first).strip("-") or "DH"
    fielding = int(m.group(2)) if m and m.group(2) else 0
    pos = POS_MAP.get(pos, pos)
    if pos.startswith("C+") or pos == "C":
        pos = "C"
    if "-" in pos and pos != "LF/RF":  # multi-position like 2B-SS: keep the first
        pos = pos.split("-")[0]
    if pos not in ("C", "1B", "2B", "3B", "SS", "LF/RF", "CF", "DH"):
        pos = "DH"
    return pos, fielding

def chart_rows(chart):
    """Rows as printed on the card; hi None means an open range ("21+")."""
    rows = []
    for key, rng in chart.items():
        if key not in RESULT_CODE:
            return None
        rows.append((rng[0], rng[1], RESULT_CODE[key]))
    rows.sort(key=lambda r: r[0])
    # verify contiguous coverage of 1..20; extend earlier rows over small gaps
    fixed = []
    cursor = 1
    for lo, hi, code in rows:
        if lo > cursor and fixed:
            prev = fixed[-1]
            fixed[-1] = (prev[0], lo - 1, prev[2])
        elif lo > cursor:
            lo = 1
        fixed.append((lo, hi, code))
        cursor = max(cursor, (hi if hi is not None else 30) + 1)
    if fixed and fixed[-1][1] is not None and fixed[-1][1] < 20:
        last = fixed[-1]
        fixed[-1] = (last[0], 20, last[2])
    return fixed

seen_ids = set()
out = []
skipped = 0
for card in cards:
    rows = chart_rows(card["chart"])
    if not rows:
        skipped += 1
        continue
    try:
        obc = int(card["obc"])
        spd_raw = card["spd"].strip()
        spd = SPEED_LETTERS.get(spd_raw, None)
        if spd is None:
            spd = int(spd_raw)
    except ValueError:
        skipped += 1
        continue
    base_id = re.sub(r"[^a-z0-9]+", "-", f"sd-{card['year'][2:]}-{card['edition']}-{card['number']}-{card['name']}".lower()).strip("-")
    card_id = base_id
    n = 2
    while card_id in seen_ids:
        card_id = f"{base_id}-{n}"
        n += 1
    seen_ids.add(card_id)
    chart_str = "|".join(f"{code}{lo}+" if hi is None else f"{code}{lo}-{hi}" for lo, hi, code in rows)
    # The card year rides with the name ("Mike Caruso '02") unless the printed
    # name already carries one (Super Season cards like "Jeff Kent '98").
    display = card["name"] if re.search(r"'\d\d$", card["name"]) else f"{card['name']} '{card['year'][2:]}"
    foil = 1 if card.get("foil") else 0
    if card["pitcher"]:
        role = "SP" if card["positions"].split("|")[0].strip().startswith("Starter") else "RP"
        out.append([card_id, display, card["team"], card["year"], card["edition"], 1, card["points"], obc, min(max(spd, 1), 9), role, 0, card["hand"], chart_str, foil, NAME_MLBAM.get(card["name"])])
    else:
        pos, fielding = primary_position(card["positions"])
        out.append([card_id, display, card["team"], card["year"], card["edition"], 0, card["points"], obc, min(max(spd, 5), 28), pos, fielding, card["hand"], chart_str, foil, NAME_MLBAM.get(card["name"])])

print(f"emitting {len(out)} cards ({skipped} skipped)", file=sys.stderr)

header = """// Real MLB Showdown cards (2000-2005), compiled from public scouting-report
// data (game-mechanical facts: points, on-base/control, speed/IP, positions,
// and chart ranges). Generated by a scraper+builder script; do not hand-edit.
// Tuple: [id, name, team, year, edition, isPitcher, points, obcOrControl,
//         speedOrIp, positionOrRole, fielding, hand, chart]
// Chart codes: P=PU K=SO G=GB F=FB W=BB S/+=1B D=2B T=3B H=HR
"""
with open(os.path.join(SP, "classicCards.js"), "w") as f:
    f.write(header)
    f.write("export const CLASSIC_CARD_ROWS = [\n")
    for row in out:
        f.write(json.dumps(row, separators=(",", ":")) + ",\n")
    f.write("];\n")
print("wrote classicCards.js", file=sys.stderr)
